# Numpy Methods

In [ ]:
import numpy as np

In [ ]:
#1. np.array() - creating a numerical data structure
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
#2. np.zero() - creating an array of zeros
a = np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
#3. np.ones() - creating an array of ones
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [ ]:
#4. np.arange() - creating a range of values
a = np.arange(1,11, 2)
a

array([1, 3, 5, 7, 9])

In [ ]:
#5. np.linspace() - evenly spaced values
a = np.linspace(0, 12, 5)
a

array([ 0.,  3.,  6.,  9., 12.])

In [ ]:
#6. np.reshape() - change shape
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
#7. np.sum() - sum of elements
a = np.sum([2, 4, 6, 8])
a

np.int64(20)

In [ ]:
#8. np.mean() - mean value
a = np.mean([2, 4, 6, 8])
a

np.float64(5.0)

In [ ]:
#9. np.median() - robust cental value
a = np.median([2, 4, 6, 8])
a

np.float64(5.0)

In [ ]:
#10. np.max() - maximum value
a = np.max([2, 4, 6, 8])
a

np.int64(8)

In [ ]:
#11. np.min() - minimum value
a = np.min([2, 4, 6, 8])
a

np.int64(2)

In [ ]:
#12. np.std() - standard deviation
a = np.std([2, 4, 6, 8])
a

np.float64(2.23606797749979)

In [ ]:
#13. np.var() - variance
a = np.var([2, 4, 6, 8])
a

np.float64(5.0)

In [ ]:
#14. np.sqrt() - square root
a = np.sqrt(64)
a

np.float64(8.0)

In [ ]:
#15. np.dot() - dot product
a = np.dot([2, 4], [6, 8])
a

np.int64(44)

In [ ]:
#16. np.sort() - sorting array
a = np.sort([2, 4, 6, 8])
a

array([2, 4, 6, 8])

In [ ]:
#17. np.unique() - unique values
a = np.unique([2, 2, 1, 1, 5, 7,9])
a

array([1, 2, 5, 7, 9])

In [ ]:
#18. np.random.randn() - simulat data
a = np.random.rand(5)
a

array([0.8691423 , 0.27177991, 0.24100017, 0.77716344, 0.93464684])

In [ ]:
#19. np.random.randint() - simulate random integers
a = np.random.randint(1,10,3)
a

array([6, 2, 9])

In [ ]:
#20. np.random.randn() - simulate random integers
a = np.random.randn(10)
a

array([-1.31533962,  1.04279307, -0.0993927 , -1.59499783, -0.48745401,
        1.39695425,  0.83737345, -1.0567493 , -0.02553127, -1.16376882])

In [ ]:
#21. np.concatenate () - join arrays
a = np.concatenate(([1, 2, 3], [4, 8, 9] ))
a

array([1, 2, 3, 4, 8, 9])

In [ ]:
#22. np.where() - Conditional selection
np.where(a > 3)

In [ ]:
#23. np.argsort() - Returns indices that would sort an array
scores = [88, 95, 70]
np.argsort(scores)

array([2, 0, 1])

In [ ]:
#24.np.percentile() - Computes percentile value
np.percentile(scores, 75)

np.float64(91.5)

In [ ]:
#25. np.quantile() - Computes quantile value
np.quantile(scores, 0.5)

np.float64(88.0)

In [ ]:
#26. np.argmax() - Returns index of maximum value
np.argmax(scores)

np.int64(1)

np.int64(2)

array([20, 30])

NameError: name 'X' is not defined

# Pandas

In [ ]:
import pandas as pd

In [ ]:
#21. pd.Series() - create series
b = pd.Series([10,20,30])
b

0    10
1    20
2    30
dtype: int64

In [ ]:
#22. pd.dataframe() - create a table without index
df = pd.DataFrame({"High":[20,40,60], "low":[14,18, 9]})
df

   High  low
0    20   14
1    40   18
2    60    9

In [ ]:
#23. pd.dataframe() - create a table with index
df1 = pd.DataFrame({"High":[100,80,60], "Meduim":[55,40,50], "low":[14,18, 9]}, index = ["Houston", "New York", "Florida"])
df1

          High  Meduim  low
Houston    100      55   14
New York    80      40   18
Florida     60      50    9

In [ ]:
#24. head() - to get the first row
df1.head(1)

         High  Meduim  low
Houston   100      55   14

In [ ]:
#25. tail() - to get the last row
df1.tail(1)

         High  Meduim  low
Florida    60      50    9

In [ ]:
#26. info() - data summary
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Houston to Florida
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   High    3 non-null      int64
 1   Meduim  3 non-null      int64
 2   low     3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [ ]:
#27. describ() - Statistical summary
df1.describe()

        High     Meduim        low
count    3.0   3.000000   3.000000
mean    80.0  48.333333  13.666667
std     20.0   7.637626   4.509250
min     60.0  40.000000   9.000000
25%     70.0  45.000000  11.500000
50%     80.0  50.000000  14.000000
75%     90.0  52.500000  16.000000
max    100.0  55.000000  18.000000

In [ ]:
#28. shape - number of rows and columns
df1.shape

(3, 3)

In [ ]:
#29. columns - columns names
df1.columns

Index(['High', 'Meduim', 'low'], dtype='object')

In [ ]:
#30. isnull() - Check missing values
df1.isnull()

           High  Meduim    low
Houston   False   False  False
New York  False   False  False
Florida   False   False  False

In [ ]:
#31. dropna() - Remove missing values
df1.dropna()

          High  Meduim  low
Houston    100      55   14
New York    80      40   18
Florida     60      50    9

In [ ]:
#32. fillna() - Fill missing values
df1.fillna(0)

          High  Meduim  low
Houston    100      55   14
New York    80      40   18
Florida     60      50    9

In [ ]:
#33. drop() - Remove rows/columns
df1.drop("High", axis=1)

          Meduim  low
Houston       55   14
New York      40   18
Florida       50    9

In [ ]:
#34. rename() - Rename columns
df1.rename(columns={"High":"Top"})

          Top  Meduim  low
Houston   100      55   14
New York   80      40   18
Florida    60      50    9

In [ ]:
#35. sort_values() - order data
df1.sort_values("low")

          High  Meduim  low
Florida     60      50    9
Houston    100      55   14
New York    80      40   18

In [ ]:
#36. loc[] - Label-based selection
df1.loc[df1["High"] > 80]

         High  Meduim  low
Houston   100      55   14

In [ ]:
#37. iloc[] - index-based selection
df1.iloc[1]

High      80
Meduim    40
low       18
Name: New York, dtype: int64

In [ ]:
#38. astype() - Change data type
df["High"].astype(float)

0    20.0
1    40.0
2    60.0
Name: High, dtype: float64

In [ ]:
#39. sum() - Sum values
df1.sum()

High      240
Meduim    145
low        41
dtype: int64

In [ ]:
#40. mean() - mean values
df1.mean()

High      80.000000
Meduim    48.333333
low       13.666667
dtype: float64